### ISSUE TITLE
Unexpected results —am I missing something from the setup?

### ISSUE THREAD

**Issue by medied** [flyswatter/human-standard-token-abi#3]
@danfinlay am pretty happy to have come across you [human-standard-token-abi package](https://www.npmjs.com/package/human-standard-token-abi) as I was having issues importing abi manually. Those issues were resolved with your package but it seems I'm missing something from the set up still as I'm not getting correct values, allow me to expand:

- working locally, `truffle develop` with port 9545
- got Metamask displaying tokens fine

<img width="355" alt="c2517a39-0ef3-49da-af56-e7b646aa00ef" src="https://user-images.githubusercontent.com/4752599/47115525-cdec2780-d22c-11e8-8197-4dedc4d4630f.png">

- code I'm testing is basically following your README, am working with a Meteor app

```
import { Meteor } from 'meteor/meteor';
import Web3 from 'web3';
import abi from 'human-standard-token-abi';

(...)

/**
* @summary gets erc20 token balance from public address
* @param {string} WIP
* @return {object} WIP
*/
const _getERC20Balance = () => {

  let balance;
  const contractAddress = token.coin[1].contractAddress; 
  const addrs = web3.eth.accounts[0];

  const contract = web3.eth.contract(abi).at(contractAddress);

  // Get the token name
  contract.name.call(function(err, name) {
    if (err) { console.log(err) }
    if (name) { console.log('The token name is: ' + name) }
  });

  // Get the token symbol
  contract.symbol.call({from: addrs}, function(err, symbol) {
    //ABI expects string here,
    if(err) { console.log(err) }
    console.log('Token symbol: ' + symbol)
  })

  // tokenSupply
  contract.totalSupply.call({from: addrs}, function(err, totalSupply) {
    console.log(totalSupply)
  })

  // balanceOf
  contract.balanceOf.call(addrs, (err, bal) => {
    if (err) { console.error(err) }
    console.log('balance is ' + bal.toNumber())
  });
};

(...)

export const getERC20Balance = _getERC20Balance;

```

- what I'm getting back from `const contract = web3.eth.contract(abi).at(contractAddress);` seems to be fine

<img width="449" alt="5dacb904-713d-4c1e-b98b-db09042d9824" src="https://user-images.githubusercontent.com/4752599/47115259-04757280-d22c-11e8-9c96-ae4b79ccc765.png">

- however, I'm not getting expected values on callbacks so evidently I'm missing something. `totalSupply()` and `balanceOf()` return empty bigNumbers/0

<img width="409" alt="c87125f7-1ca7-4924-ad3f-25abc8ebf1d9" src="https://user-images.githubusercontent.com/4752599/47115293-253dc800-d22c-11e8-85f7-15146714130e.png">
<img width="411" alt="77e43294-c768-4812-8070-306cb73dd3c6" src="https://user-images.githubusercontent.com/4752599/47115301-28d14f00-d22c-11e8-83c6-4c018fedfa3c.png">

- and getting the sting error on symbol and name

<img width="449" alt="b6604823-2dea-4eb2-a034-31fc0fa19248" src="https://user-images.githubusercontent.com/4752599/47115360-5e763800-d22c-11e8-8acb-92547116e1ad.png">
<img width="443" alt="3a32e0d7-0121-489e-86c5-0329e4f27aa5" src="https://user-images.githubusercontent.com/4752599/47115375-63d38280-d22c-11e8-8ee0-8125d064ec02.png">

- Constructing abi manually I was able to successfully read `balanceOf` in the Chrome console though

<img width="815" alt="289df4f3-8fff-443e-8d7e-ebb52ceaa31f" src="https://user-images.githubusercontent.com/4752599/47115584-055ad400-d22d-11e8-918c-85a779f20e82.png">

Hope this is making sense. Should I take care of working in client/server side in Meteor? Any ideas on what I could be missing?

**Comment by medied** [comment]
Forgot to state am using web3 v0.20.7

**Comment by conorwatt1** [comment]
Take a look at:

ethjs -> https://github.com/ethjs

bignumberJS -> https://github.com/MikeMcl/bignumber.js/

*NOTE:* I found that with web3 if I needed to make a call for token symbol,
token balance, total supply etc I would have to set something like
setTimeout to wait for a response (sometimes its a little slow)

**Comment by medied** [comment]
thanks @conorwatt1, ended up figuring out the issue was in web3 provider setup
